accounts/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from django.views.generic import TemplateView
from .views import index, email_exists, CreateAccountView, DeleteAccountView, AccountListView

urlpatterns = [
    path("email-exists", email_exists, name="email-exists"),
    path("create", CreateAccountView.as_view(), name="create-account"),
    path("delete", DeleteAccountView.as_view(), name="delete-account"),
    path("list", AccountListView.as_view(), name="list-account"),
    path("", index, name="list-account-html"),
]

books/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from django.views.generic import TemplateView
from .views import books_api, add, google_signin, logout, get_profile, delete, get

urlpatterns = [
    path("api/favorites/get", get, name="list-favorites"),  
    path("api/favorites/add", add, name="add-favorites"),  
    path("api/favorites/delete", delete, name="delete-favorites"),  
    path("api/profile/", get_profile, name="login-google"),  
    path("api/login-google/", google_signin, name="login-google"),  
    path("api/logout/", logout, name="logout"),  
    path("api", books_api, name="list-books"),
    path("", TemplateView.as_view(template_name="books/index.html"), name="index"),
]

hello/urls.py
from django.conf.urls import include
from django.urls import path
from django.contrib import admin
from . import views

app_name = "hello"

urlpatterns = [path(r"", views.index, name="index")]

me/urls.py
from django.urls import path
from . import views

# url for app, add your URL Configuration
app_name = "me"

urlpatterns = [path("posts", views.post_list, name="posts"), path("", views.index, name="index")]

praktikum/urls.py
from django.conf.urls import include
from django.urls import re_path,path
from django.contrib import admin


urlpatterns = [
    re_path(r"^admin/", admin.site.urls),
    re_path(r"", include("hello.urls")),
    path("books/", include("books.urls")),
    path("accounts/", include("accounts.urls")),
    re_path(r"^profile/", include("me.urls")),
]

accounts/models.py
from django.db import models
from django.core.exceptions import ValidationError


class User(models.Model):
    name = models.CharField(max_length=100)
    email = models.EmailField(unique=True)
    password = models.CharField(max_length=32)

    @classmethod
    def is_email_exists(cls, email):
        return cls.objects.filter(email=email).exists()

    @classmethod
    def delete_user(cls, email, password):
        user = cls.objects.filter(email=email, password=password).first()
        if user:
            user.delete()

hello/models.py
from django.db import models


class Status(models.Model):
    message = models.CharField(max_length=300)
    date_created = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ["-date_created"]

me/models.py
from django.db import models

# Create your models here.

accounts/forms.py
from django import forms
from .models import User


class CreateUserForm(forms.ModelForm):
    class Meta:
        model = User
        fields = "__all__"
        widgets = {"password": forms.PasswordInput()}


class DeleteUserForm(forms.Form):
    email = forms.EmailField()
    password = forms.CharField(max_length=32)

hello/forms.py
from django import forms
from .models import Status


class StatusForm(forms.ModelForm):
    class Meta:
        model = Status
        fields = "__all__"

accounts/views.py
from django.shortcuts import render
from django.http import JsonResponse, QueryDict
from django.views import View
from .models import User
from .forms import CreateUserForm, DeleteUserForm


def email_exists(request):
    return JsonResponse({"exists": User.is_email_exists(request.GET.get("email"))})


def index(request):
    return render(request, "accounts/index.html")


class CreateAccountView(View):
    def get(self, request):
        return render(request, "accounts/create.html", {"form": CreateUserForm()})

    def post(self, request):
        form = CreateUserForm(request.POST)
        if form.is_valid():
            form.save()
        return JsonResponse({"success": form.is_valid(), "errors": form.errors.as_json()})


class DeleteAccountView(View):
    def post(self, request):
        form = DeleteUserForm(request.POST)
        success = False
        if form.is_valid():
            data = form.cleaned_data
            success = bool(
                User.objects.filter(email=data["email"], password=data["password"]).delete()[0]
            )
        return JsonResponse({"success": success})


class AccountListView(View):
    def get(self, request):
        return JsonResponse(list(User.objects.values("name", "email")), safe=False)

books/views.py
import requests
from django.http import JsonResponse
from django.views import View


def books_api(request):
    url = f'https://www.googleapis.com/books/v1/volumes?q={request.GET["q"]}'
    return JsonResponse(requests.get(url).json())


def get(request):
    return JsonResponse(request.session.get('books', []), safe=False)


def add(request):
    response = {"success": False}
    books = request.session['books'] = request.session.get('books', [])
    if request.method != "POST":
        response["message"] = "invalid method"
    elif not request.POST.get("id"):
        response["message"] = "please provide an id"
    else:
        books.append(request.POST["id"])
        response["success"] = True
    print(response)
    return JsonResponse(response)


def delete(request):
    response = {"success": False}
    books = request.session['books'] = request.session.get('books', [])
    if request.method != "POST":
        response["message"] = "invalid method"
    elif not request.POST.get("id"):
        response["message"] = "please provide an id"
    else:
        books.remove(request.POST["id"])
        response["success"] = True
    return JsonResponse(response)


def google_signin(request):
    if request.method != "POST":
        return JsonResponse({"success":False, "message":"Invalid method"})
    token = request.POST.get("id_token")
    if not token:
        return JsonResponse({"success":False, "message":"Invalid id_token"})
    # Security iz my pession <3
    request.session["id_token"] = token
    request.session["name"] = request.POST.get("name")
    request.session["image_url"] = request.POST.get("image_url")
    return JsonResponse({"success":True})


def logout(request):
    if request.method == "POST":
        request.session.flush()
        return JsonResponse({"success": True})
    return JsonResponse({"success":False, "message":"Invalid method"})


def get_profile(request):
    return JsonResponse({
        "name": request.session.get('name'),
        "image_url": request.session.get('image_url')
    })  

hello/views.py
from django.shortcuts import render, redirect
from .models import Status
from .forms import StatusForm

# Create your views here.
def index(request):
    form = StatusForm()
    if request.method == "POST":
        form = StatusForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect("hello:index")

    status_list = Status.objects.all()
    context = {"form": form, "status_list": status_list}
    return render(request, "hello/index.html", context)

me/views.py
from django.shortcuts import render
from django.http import HttpResponse


def index(request):
    return render(request, "me/index.html", {})


def post_list(request):
    return render(request, "me/blog_list.html", {})

accounts/templates/accounts/create.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="{% static 'css/accounts.css'%}" />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto"
      rel="stylesheet"
    />
    <title>Subscribe</title>
  </head>
  <body>
    <form class="Form" action="/accounts/create" method="POST">
      <h1 class="Form__title">Subscribe Now</h1>
      {% csrf_token %} {% for field in form %}
      <div class="Form__field">
        {{ field.label_tag }} {{ field }}
        <div class="errors" id="errors_{{field.name}}"></div>
      </div>
      {% endfor %} <button class="Form__button">Sign Up</button>
      <div class="success hidden">Account successfully created.</div>
    </form>
  </body>
  <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"
  ></script>
  <script src="{% static 'js/accounts.min.js' %}"></script>
</html>

accounts/templates/accounts/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="{% static 'css/accounts.css'%}" />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto"
      rel="stylesheet"
    />
    <title>Create Account</title>
  </head>
  <body>
    <div class="Form">
      <h1 class="Form__title">Subscribers</h1>
      <a class="Subscribe" href="/accounts/create">Become a subscriber</a>
      <table>
        <thead>
          <tr>
            <th>Name</th>
            <th>Email</th>
            <th>Action</th>
          </tr>
        </thead>
        <tbody class="table-content">
          <tr>
            <td>Loading...</td>
          </tr>
        </tbody>
      </table>
    </div>
  </body>
  <script
    src="https://code.jquery.com/jquery-3.3.1.min.js"
    integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"
  ></script>
  <script src="{% static 'js/accounts_index.js' %}"></script>
</html>

books/templates/books/index.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta http-equiv="X-UA-Compatible" content="ie=edge" />
    <link rel="stylesheet" href="{% static 'css/books.css'%}" />
    <link
      href="https://fonts.googleapis.com/css?family=Roboto"
      rel="stylesheet"
    />
    <title>Books</title>
  </head>
  <body>
    <div class="books-head">
      <div class="title">Welcome <span id="username">Anonymous</span></div>
      <div>
        <input value="quilting" id="searchBox" /><button id="searchButton">
          Search
        </button>
      </div>
      <div class="subtitle">Favorites: <span id="favoriteCount">0</span></div>
    </div>
    <div></div>
    <table>
      <thead>
        <tr>
          <th>Title</th>
          <th>Authors</th>
          <th>Publisher</th>
          <th>Favorite</th>
        </tr>
      </thead>
      <tbody class="table-content">
        <tr>
          <td>Loading...</td>
        </tr>
      </tbody>
    </table>
  </body>
  <script src="{% static 'js/books.js' %}"></script>
  <div class="g-signin2" data-onsuccess="onSignIn"></div>
  <a href="#" onclick="signOut();">Sign out</a>
  <script src="https://apis.google.com/js/platform.js" async defer></script>
  <meta name="google-signin-client_id" content="839022262183-rnne81g4p8j2ghpn7hsq13ep9p5f1bdd.apps.googleusercontent.com">
</html>

hello/templates/hello/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.3/css/bootstrap.min.css" integrity="sha384-MCw98/SFnGE8fJT3GXwEOngsV7Zt27NXFoaoApmYm81iuXoPkFOJwJ8ERdknLPMO"
        crossorigin="anonymous">
    <title>Hello</title>
</head>

<body>
    <h1>Hello, Apa kabar?</h1>

    {% if status_list %}
    {% for status in status_list %}
    <div>
        <p>{{status.date_created | date:"H.i, j F"}}</p>
        <p>{{status.message}}</p>
    </div>
    {% endfor %}

    {% else %}
    <p>Semua status akan ditampilkan di sini.</p>
    {% endif %}

    <form action={% url 'hello:index' %} method="post">
        <h2>Buat status baru</h2>
        {% csrf_token %}
        {{ form.as_p }}
        <input type="submit" value="Buat Status">
    </form>
</body>

</html>

me/templates/me/base.html
{% load static %}

<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>Raihan Ramadistra</title>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
    <link rel="stylesheet" type="text/css" media="screen" href={% static "main.css" %} />
</head>

<style>
    .lds-dual-ring {
        display: block;
        width: 64px;
        height: 64px;
        margin: auto;
    }

    .lds-dual-ring:after {
        content: " ";
        display: block;
        width: 46px;
        height: 46px;
        margin: 1px;
        border-radius: 50%;
        border: 5px solid #000;
        border-color: #000 transparent #000 transparent;
        animation: lds-dual-ring 1.2s linear infinite;
    }

    @keyframes lds-dual-ring {
        0% {
            transform: rotate(0deg);
        }

        100% {
            transform: rotate(360deg);
        }
    }
</style>

<body class="PaneLayout">
    <div class="content">
        <div class="content__Container">
            {% include "me/navbar.html" %}
            <div id="spinner" class="lds-dual-ring">
            </div>
            {% block content %}{% endblock %}
        </div>
    </div>
    {% include "me/sidebar.html" %}
</body>
<script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8="
    crossorigin="anonymous"></script>
<script src={% static "js/main.js" %}></script>

</html>

me/templates/me/blog_list.html
{% extends "me/base.html" %}

{% block content %}
<div class="content__Section">
    <div class="content__Section__title">
        Tulisan Saya
    </div>
    <div class="content__Section__Item">
        <div class="content__Section__Item__main">
            <div>PPW Sangat Menyenangkan</div>
            <div class="content__Subtext">Pengalamanku belajar PPW yang sangat menyenangkan.</div>
        </div>
        <div class="content__Section__Item__side">
            <div>9 Sep</div>
            <div class="CommentCount"> 1
                <i class="material-icons sidebar__Icon">
                    comment
                </i>
            </div>
        </div>
    </div>
    <div class="content__Section__Item">
        <div class="content__Section__Item__main">
            <div>PPW Sangat Menyenangkan</div>
            <div class="content__Subtext">Pengalamanku belajar PPW yang sangat menyenangkan.</div>
        </div>
        <div class="content__Section__Item__side">
            <div>9 Sep</div>
            <div class="CommentCount"> 1
                <i class="material-icons sidebar__Icon">
                    comment
                </i>
            </div>
        </div>
    </div>
    <div class="content__Section__Item">
        <div class="content__Section__Item__main">
            <div>PPW Sangat Menyenangkan</div>
            <div class="content__Subtext">Pengalamanku belajar PPW yang sangat menyenangkan.</div>
        </div>
        <div class="content__Section__Item__side">
            <div>9 Sep</div>
            <div class="CommentCount"> 1
                <i class="material-icons sidebar__Icon">
                    comment
                </i>
            </div>
        </div>
    </div>
    <div class="content__Section__Item">
        <div class="content__Section__Item__main">
            <div>PPW Sangat Menyenangkan</div>
            <div class="content__Subtext">Pengalamanku belajar PPW yang sangat menyenangkan.</div>
        </div>
        <div class="content__Section__Item__side">
            <div>9 Sep</div>
            <div class="CommentCount"> 1
                <i class="material-icons sidebar__Icon">
                    comment
                </i>
            </div>
        </div>
    </div>
    <div class="content__Section__Item">
        <div class="content__Section__Item__main">
            <div>PPW Sangat Menyenangkan</div>
            <div class="content__Subtext">Pengalamanku belajar PPW yang sangat menyenangkan.</div>
        </div>
        <div class="content__Section__Item__side">
            <div>9 Sep</div>
            <div class="CommentCount"> 1
                <i class="material-icons sidebar__Icon">
                    comment
                </i>
            </div>
        </div>
    </div>
    <div class="content__Section__Item">
        <div class="content__Section__Item__main">
            <div>PPW Sangat Menyenangkan</div>
            <div class="content__Subtext">Pengalamanku belajar PPW yang sangat menyenangkan.</div>
        </div>
        <div class="content__Section__Item__side">
            <div>9 Sep</div>
            <div class="CommentCount">
                1<i class="material-icons sidebar__Icon">comment</i>
            </div>
        </div>
    </div>
</div>
{% endblock %}

me/templates/me/index.html
{% extends "me/base.html" %}

{% block content %}
<div class="content__Section">
    <div class="content__Section__title">
        Pendidikan
    </div>
    <div class="content__Section__Item">
        <div class="content__Section__Item__main">
            <div>Ilmu Komputer</div>
            <div>Universitas Indonesia – Depok, Jawa Barat</div>
        </div>
        <div class="content__Section__Item__side">
            Ags 2017 – Jun 2021
        </div>
    </div>
</div>
<div class="Divider"></div>

<div class="content__Section">
    <div class="content__Section__title">
        Pengalaman
    </div>
    <div class="content__Section__Item">
        <div class="content__Section__Item__main">
            <div>Pemagang Rekayasa Perangkat Lunak</div>
            <div>Tokopedia.com – Jakarta Selatan, DKI Jakarta</div>
        </div>
        <div class="content__Section__Item__side">
            <div>Jun 2018 – Sep 2018</div>
        </div>
    </div>
    <div class="content__Section__Item">
        <div class="content__Section__Item__main">
            <div>Pemagang Rekayasa Bagian Belakang</div>
            <div>Qlapa.com – Jakarta Barat, DKI Jakarta</div>
        </div>
        <div class="content__Section__Item__side">
            <div>Jan 2018 – Feb 2018</div>
        </div>
    </div>
    <div class="content__Section__Item">
        <div class="content__Section__Item__main">
            <div>Pemagang Rekayasa Perangkat Lunak</div>
            <div>PRASIMAX – Depok, Jawa Barat</div>
        </div>
        <div class="content__Section__Item__side">
            <div>Jul 2017 – Des 2017</div>
        </div>
    </div>
</div>
<div class="Divider"></div>


<div class="content__Section">
    <div class="content__Section__title">
        Kegiatan
    </div>
    <div class="content__Section__Item">
        <div class="content__Section__Item__main">
            <div>Staf</div>
            <div>Divisi Pengembangan TI, Compfest X</div>
        </div>
        <div class="content__Section__Item__side">
            <div>Feb 2018 – Sekarang</div>
        </div>
    </div>
    <div class="content__Section__Item">
        <div class="content__Section__Item__main">
            <div>Anggota Junior</div>
            <div>Keamanan Jaringan, RISTEK Fasilkom</div>
        </div>
        <div class="content__Section__Item__side">
            <div>Feb 2018 – Sekarang</div>
        </div>
    </div>
</div>
<div class="Divider"></div>

<div class="content__Section">
    <div class="content__Section__title">
        Prestasi
    </div>
    <div class="content__Section__Item">
        <div class="content__Section__Item__main">
            <div>Finalis CTF Slashroot 3.0</div>
            <div>Lomba Keamanan Jaringan oleh STIKOM Bali</div>
        </div>
        <div class="content__Section__Item__side">
            <div>Ags 2018</div>
        </div>
    </div>
    <div class="content__Section__Item">
        <div class="content__Section__Item__main">
            <div>Finalis CTF Arkavidia 4</div>
            <div>Lomba Keamanan Jaringan oleh ITB</div>
        </div>
        <div class="content__Section__Item__side">
            <div>Feb 2018</div>
        </div>
    </div>
</div>
{% endblock content %}

me/templates/me/navbar.html
<nav>
    <a href={% url 'me:index' %}>Profil</a>
    <a href={% url 'me:posts' %}>Blog</a>
    <div>
        <span>Theme: </span>
        <select id="themeSelector">
            <option value="blue">Blue
            <option value="green">Green
        </select>
    </div>
</nav>
<div class="Divider"></div>

me/templates/me/sidebar.html
{% load static %}

<div class="sidebar">
    <div class="sidebar__Container">
        <div class="sidebar__Profile">
            <img src="{% static 'foto.jpeg' %}" />
            <figcaption>
                <div class="sidebar__Title">
                    Raihan Ramadistra
                </div>
                <div class="sidebar__Profile__info">
                    <div>Mahasiswa S1</div>
                    <div>Ilmu Komputer</div>
                </div>
            </figcaption>
        </div>
        <div class="sidebar__Bio">
            Saya adalah mahasiswa S1 Ilmu Komputer semester 3 di Universitas Indonesia. Saya memiliki minat di
            bidang rekayasa perangkat lunak, dengan pengalaman rekayasa bagian depan dan bagian belakang. Saya juga
            suka mengikuti lomba keamanan jaringan bersama teman-teman saya.
        </div>
        <div class="Divider"></div>
        <div class="sidebar__RecentBlog">
            <div class="sidebar__Title">
                Tulisan Terbaru
            </div>
            <div class="sidebar__RecentBlog__Post">
                <article>
                    <div>PPW sangat menyenangkan</div>
                    <div>4 hari yang lalu</div>
                </article>
                <aside>
                    1 <i class="material-icons sidebar__Icon">
                        comment
                    </i>
                </aside>
            </div>
            <div class="sidebar__RecentBlog__Post">
                <article>
                    <div>PPW sangat menyenangkan</div>
                    <div>4 hari yang lalu</div>
                </article>
                <aside>
                    10 <i class="material-icons sidebar__Icon">
                        comment
                    </i>
                </aside>
            </div>
            <div class="sidebar__RecentBlog__SeeMore">
                <a class="sidebar__RecentBlog__Button" href={% url 'me:posts' %}>Lihat Selengkapnya ></a>
            </div>
        </div>
    </div>
    <footer>
        <div class="sidebar__Social">
            <div>
                <a href="mailto:ramadistra@gmail.com">
                    <svg width="32" height="24" viewBox="0 0 37 28" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M32.987 0H3.66522C1.64019 0 0.0183261 1.56625 0.0183261 3.5L0 24.5C0 26.432 1.64019 28 3.66522 28H32.987C35.012 28 36.6522 26.432 36.6522 24.5V3.5C36.6522 1.56625 35.012 0 32.987 0Z"
                            fill="white" />
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M32.9868 24.5H29.3216V9.1875L18.3259 15.75L7.33026 9.1875V24.5H3.66504V3.5H5.86417L18.3259 10.9375L30.7877 3.5H32.9868V24.5Z"
                            fill="#298ED8" />
                    </svg>
                </a>
            </div>
            <div>
                <a target="_blank" href="https://twitter.com/ramadistra">
                    <svg width="32" height="27" viewBox="0 0 36 30" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path d="M11.3216 29.1544C24.9072 29.1544 32.3366 17.939 32.3366 8.21345C32.3366 7.89489 32.3301 7.57778 32.3157 7.2621C33.7579 6.22321 35.0113 4.92677 36 3.45094C34.6766 4.03711 33.2524 4.4317 31.7585 4.60963C33.2834 3.69846 34.4541 2.25709 35.0064 0.538813C33.5793 1.38183 31.999 1.99454 30.3163 2.32534C28.9685 0.894771 27.0497 0 24.925 0C20.8461 0 17.5385 3.29607 17.5385 7.35894C17.5385 7.93649 17.6033 8.49827 17.7301 9.03713C11.5914 8.72933 6.14813 5.80065 2.50517 1.34739C1.87086 2.43505 1.5051 3.69849 1.5051 5.04661C1.5051 7.60006 2.80905 9.85426 4.79193 11.173C3.58014 11.1357 2.44181 10.8042 1.44687 10.2525C1.44578 10.2834 1.44578 10.3135 1.44578 10.3465C1.44578 13.9109 3.99172 16.8868 7.37133 17.5612C6.75068 17.7298 6.09769 17.8202 5.42373 17.8202C4.94853 17.8202 4.48556 17.7736 4.03557 17.6875C4.97588 20.6118 7.70256 22.7399 10.9353 22.7993C8.40733 24.7738 5.22283 25.9497 1.76181 25.9497C1.16637 25.9497 0.57813 25.916 0 25.8479C3.26883 27.9357 7.15025 29.1539 11.322 29.1539"
                            fill="white" />
                    </svg>
                </a>
            </div>
            <div>
                <a target="_blank" href="https://linkedin.com/in/ramadistra">
                    <img width="30" height="30" src={% static "linkedin.png" %}>
                </a>
            </div>
            <div>
                <a target="_blank" href="https://github.com/ramadistra">
                    <svg width="32" height="30" viewBox="0 0 38 36" fill="none" xmlns="http://www.w3.org/2000/svg">
                        <path fill-rule="evenodd" clip-rule="evenodd" d="M18.4565 0C8.26579 0 0 8.26079 0 18.4453C0 26.593 5.32181 33.4958 12.5685 35.9854C13.4744 36.0985 13.8141 35.5327 13.8141 35.0801C13.8141 34.6274 13.8141 33.4958 13.8141 31.9115C8.71872 33.0432 7.58641 29.422 7.58641 29.422C6.7938 27.2719 5.54827 26.7061 5.54827 26.7061C3.84982 25.5745 5.6615 25.5745 5.6615 25.5745C7.47319 25.6877 8.49226 27.4982 8.49226 27.4982C10.1907 30.3273 12.795 29.5352 13.8141 29.0825C13.9273 27.8377 14.4934 27.0456 14.9464 26.593C10.8701 26.1403 6.56734 24.556 6.56734 17.4269C6.56734 15.39 7.24672 13.8057 8.49226 12.4478C8.37903 12.1083 7.69965 10.1845 8.71872 7.69498C8.71872 7.69498 10.3039 7.24234 13.8141 9.61873C15.2861 9.16608 16.8713 9.05292 18.4565 9.05292C20.0417 9.05292 21.6269 9.27924 23.0989 9.61873C26.6091 7.24234 28.1943 7.69498 28.1943 7.69498C29.2134 10.1845 28.534 12.1083 28.4207 12.5609C29.5531 13.8057 30.3457 15.5031 30.3457 17.54C30.3457 24.6692 26.0429 26.1403 21.9666 26.593C22.646 27.1588 23.2122 28.2904 23.2122 29.9878C23.2122 32.4774 23.2122 34.4011 23.2122 35.0801C23.2122 35.5327 23.5519 36.0985 24.4577 35.9854C31.8177 33.4958 37.0262 26.593 37.0262 18.4453C36.913 8.26079 28.6472 0 18.4565 0Z"
                            fill="white" />
                    </svg>
                </a>
            </div>
        </div>
        <div>Raihan Ramadistra – 2018</div>
    </footer>
</div>